# backend/routes/scan.py
# Core scan processing pipeline — the main entry point for the MedEcho workflow.
#
# When a clinician uploads a scan, this endpoint orchestrates the full pipeline:
#   1. Save the uploaded image
#   2. Run DenseNet CNN classification (condition, confidence, urgency, differential)
#   3. Generate GradCAM heatmap at original scan resolution
#   4. Match recruiting clinical trials from ClinicalTrials.gov
#   5. Call Gemini to generate clinical report + patient scripts
#   6. Save the complete patient record as JSON
#   7. Return everything to the clinician portal
#
# The patient record is then served to the physician and patient portals
# via /api/patient/<patient_id>.

import os
import json
import requests
from flask import Blueprint, request, jsonify
import sys
sys.path.append('.')
from medecho_model.classifier import classify_scan, xrv_model
from medecho_model.gradcam import generate_heatmap
from services.trials import get_matched_trials

scan_bp = Blueprint('scan', __name__)

# Base directory is one level up from routes/ → points to backend/
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_generation(dob_str: str) -> str:
    """
    Maps a date of birth string to a generational cohort.

    Used by Gemini to tailor the tone and vocabulary of patient-facing scripts:
    - Silent Generation → very formal, gentle
    - Baby Boomer       → formal, thorough, authoritative
    - Gen X             → direct, no-nonsense, factual
    - Millennial        → empathetic, collaborative, explains the why
    - Gen Z             → transparent, plain spoken, direct

    Args:
        dob_str: Date string in YYYY-MM-DD format (e.g. "1988-04-15")

    Returns:
        Generation label string, or "General" if DOB is missing or unparseable
    """
    if not dob_str:
        return "General"
    try:
        birth_year = int(dob_str.split('-')[0])
        if birth_year <= 1945:
            return "Silent Generation"
        elif birth_year <= 1964:
            return "Baby Boomer"
        elif birth_year <= 1980:
            return "Gen X"
        elif birth_year <= 1996:
            return "Millennial"
        else:
            return "Gen Z"
    except:
        return "General"


@scan_bp.route('/api/scan', methods=['POST'])
def scan():
    """
    Processes a chest X-ray or skin image submission from the clinician portal.

    Expects multipart/form-data with:
        image           - The uploaded scan file (PNG or JPG)
        patient_id      - UUID generated by the clinician portal (e.g. "P-xxxx")
        patient_name    - Patient's full name
        language        - Language code: "en", "es", "fr", or "hi"
        patient_location - Patient's city for clinical trial geographic matching
        patient_dob     - Date of birth in YYYY-MM-DD format for generation detection
        symptoms        - Comma-separated symptom description for trial matching
        clinician_notes - Optional clinical context from the clinician

    Returns:
        200 - Full patient record JSON including scan results, heatmap URL,
              matched trials, and Gemini-generated scripts
        400 - { "error": "No image uploaded" } if image is missing
    """

    # Step 1: Validate image upload
    if 'image' not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    # Step 2: Extract form fields
    image = request.files['image']
    patient_id = request.form.get('patient_id', 'P001')
    patient_name = request.form.get('patient_name', 'Unknown')
    language = request.form.get('language', 'en')
    patient_location = request.form.get('patient_location', '')
    patient_dob = request.form.get('patient_dob', '')
    generation = get_generation(patient_dob)

    # Step 3: Save the uploaded image to static/scans/
    scan_dir = os.path.join(BASE_DIR, 'static', 'scans')
    os.makedirs(scan_dir, exist_ok=True)
    image_path = os.path.join(scan_dir, f"{patient_id}.png")
    image.save(image_path)

    # Step 4: Run DenseNet classifier
    # Returns condition, confidence, urgency, differential diagnosis
    # return_tensors=True also returns img_tensor and img_np for GradCAM
    result = classify_scan(image_path, return_tensors=True)
    img_tensor = result.pop("_img_tensor")
    img_np = result.pop("_img_np")

    # Step 5: Generate GradCAM heatmap at original scan resolution
    # Highlights the image regions that drove the AI prediction
    heatmap_path = generate_heatmap(img_tensor, img_np, xrv_model, image_path)
    heatmap_filename = os.path.basename(heatmap_path)

    # Step 6: Match recruiting clinical trials from ClinicalTrials.gov
    # Uses multi-factor scoring: condition, differential, symptoms, location, language, phase
    trials = get_matched_trials(
        condition=result["condition"],
        location=patient_location,
        differential=result.get("differential_diagnosis", []),
        symptoms=request.form.get('symptoms', ''),
        language=language
    )

    # Step 7: Assemble the patient record with all metadata
    result['patient_id'] = patient_id
    result['patient_name'] = patient_name
    result['image_url'] = f"/files/scans/{patient_id}.png"
    result['heatmap_url'] = f"/files/heatmaps/{heatmap_filename}"
    result['trials'] = trials
    result['language'] = language
    result['clinician_notes'] = request.form.get('clinician_notes', '')
    result['physician_notes'] = ""       # Filled in by /api/approve
    result['phase'] = 1                  # Transitions to 2 after physician sends
    result['patient_location'] = patient_location
    result['patient_dob'] = patient_dob
    result['generation'] = generation
    result['symptoms'] = request.form.get('symptoms', '')

    # Step 8: Call Gemini via /api/explain to generate all three text outputs
    # - clinical_report: formal physician-facing summary
    # - phase1_script:   warm pre-review patient message
    # - phase2_script:   plain-language post-review explanation (overridden by /api/approve)
    try:
        explain_res = requests.post(
            "http://127.0.0.1:5000/api/explain",
            json={
                "patient_id": patient_id,
                "condition": result["condition"],
                "confidence": result["confidence"],
                "urgency": result["urgency"],
                "language": language,
                "generation": generation
            },
            timeout=30
        )
        explain_data = explain_res.json()
        result['clinical_report'] = explain_data.get('clinical_report', '')
        result['phase1_script'] = explain_data.get('phase1_script', '')
        result['phase2_script'] = explain_data.get('phase2_script', '')
    except Exception as e:
        # Graceful fallback — scan still succeeds without Gemini content
        print(f"Gemini explain error: {e}")
        result['clinical_report'] = ''
        result['phase1_script'] = ''
        result['phase2_script'] = ''

    # Step 9: Persist the complete patient record to disk
    data_dir = os.path.join(BASE_DIR, 'static', 'data')
    os.makedirs(data_dir, exist_ok=True)
    with open(os.path.join(data_dir, f"{patient_id}.json"), 'w') as f:
        json.dump(result, f)

    return jsonify(result)